name: CI Pipeline

on:
  push:
    branches:
      - task-1
  pull_request:
    branches:
      - task-1

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest depending on your environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'  # Specify Python 3.12.0 explicitly

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          # Run your tests here, for example:
          pytest
